import 'package:flutter/cupertino.dart';

import 'source_edit_legacy_field_section.dart';
import 'source_edit_legacy_form_controllers.dart';

class SourceEditLegacyTabBuilder {
  static const Map<String, String> _fieldLabels = <String, String>{
    'bookSourceUrl': '书源地址',
    'bookSourceName': '书源名称',
    'bookSourceGroup': '书源分组',
    'bookSourceComment': '备注',
    'loginUrl': '登录地址',
    'loginUi': '登录界面',
    'loginCheckJs': '登录校验JS',
    'coverDecodeJs': '封面解码JS',
    'bookUrlPattern': '书籍地址匹配',
    'header': '请求头',
    'variableComment': '变量说明',
    'concurrentRate': '并发率',
    'jsLib': 'JS库',
    'searchUrl': '搜索地址',
    'checkKeyWord': '关键词',
    'bookList': '书籍列表',
    'name': '书名',
    'author': '作者',
    'kind': '分类',
    'wordCount': '字数',
    'lastChapter': '最新章节',
    'intro': '简介',
    'coverUrl': '封面地址',
    'bookUrl': '书籍地址',
    'exploreUrl': '发现地址',
    'init': '详情初始化',
    'tocUrl': '目录地址',
    'canReName': '书名可改',
    'downloadUrls': '下载地址规则',
    'preUpdateJs': '目录预处理JS',
    'chapterList': '章节列表',
    'chapterName': '章节名',
    'chapterUrl': '章节地址',
    'formatJs': '格式化JS',
    'isVolume': '卷标记',
    'updateTime': '更新时间',
    'isVip': 'VIP标记',
    'isPay': '付费标记',
    'nextTocUrl': '下一页目录',
    'content': '正文内容',
    'title': '正文标题',
    'nextContentUrl': '下一页正文',
    'webJs': 'WebView JS',
    'sourceRegex': '替换源正则',
    'replaceRegex': '替换规则',
    'imageStyle': '图片样式',
    'imageDecode': '图片解码',
    'payAction': '购买动作',
  };

  static List<Widget> buildTabs({
    required SourceEditLegacyFormControllers form,
    required TextEditingController? activeFieldController,
    required void Function(String key, TextEditingController controller)
        onFieldActivated,
    required VoidCallback onShowInsertActions,
  }) {
    return <Widget>[
      _buildRuleTabSection(
        title: '基础信息',
        fields: <SourceEditLegacyFieldSpec>[
          SourceEditLegacyFieldSpec(key: 'bookSourceUrl', controller: form.bookSourceUrlCtrl),
          SourceEditLegacyFieldSpec(key: 'bookSourceName', controller: form.bookSourceNameCtrl),
          SourceEditLegacyFieldSpec(key: 'bookSourceGroup', controller: form.bookSourceGroupCtrl),
          SourceEditLegacyFieldSpec(key: 'bookSourceComment', controller: form.bookSourceCommentCtrl, maxLines: 3),
          SourceEditLegacyFieldSpec(key: 'loginUrl', controller: form.loginUrlCtrl),
          SourceEditLegacyFieldSpec(key: 'loginUi', controller: form.loginUiCtrl, maxLines: 3),
          SourceEditLegacyFieldSpec(key: 'loginCheckJs', controller: form.loginCheckJsCtrl, maxLines: 3),
          SourceEditLegacyFieldSpec(key: 'coverDecodeJs', controller: form.coverDecodeJsCtrl, maxLines: 3),
          SourceEditLegacyFieldSpec(key: 'bookUrlPattern', controller: form.bookUrlPatternCtrl),
          SourceEditLegacyFieldSpec(key: 'header', controller: form.headerCtrl, maxLines: 3),
          SourceEditLegacyFieldSpec(key: 'variableComment', controller: form.variableCommentCtrl, maxLines: 2),
          SourceEditLegacyFieldSpec(key: 'concurrentRate', controller: form.concurrentRateCtrl),
          SourceEditLegacyFieldSpec(key: 'jsLib', controller: form.jsLibCtrl, maxLines: 4),
        ],
        activeFieldController: activeFieldController,
        onFieldActivated: onFieldActivated,
        onShowInsertActions: onShowInsertActions,
      ),
      _buildRuleTabSection(
        title: '搜索规则',
        fields: <SourceEditLegacyFieldSpec>[
          SourceEditLegacyFieldSpec(key: 'searchUrl', controller: form.searchUrlCtrl),
          SourceEditLegacyFieldSpec(key: 'checkKeyWord', controller: form.searchCheckKeyWordCtrl),
          SourceEditLegacyFieldSpec(key: 'bookList', controller: form.searchBookListCtrl),
          SourceEditLegacyFieldSpec(key: 'name', controller: form.searchNameCtrl),
          SourceEditLegacyFieldSpec(key: 'author', controller: form.searchAuthorCtrl),
          SourceEditLegacyFieldSpec(key: 'kind', controller: form.searchKindCtrl),
          SourceEditLegacyFieldSpec(key: 'wordCount', controller: form.searchWordCountCtrl),
          SourceEditLegacyFieldSpec(key: 'lastChapter', controller: form.searchLastChapterCtrl),
          SourceEditLegacyFieldSpec(key: 'intro', controller: form.searchIntroCtrl),
          SourceEditLegacyFieldSpec(key: 'coverUrl', controller: form.searchCoverUrlCtrl),
          SourceEditLegacyFieldSpec(key: 'bookUrl', controller: form.searchBookUrlCtrl),
        ],
        activeFieldController: activeFieldController,
        onFieldActivated: onFieldActivated,
        onShowInsertActions: onShowInsertActions,
      ),
      _buildRuleTabSection(
        title: '发现规则',
        fields: <SourceEditLegacyFieldSpec>[
          SourceEditLegacyFieldSpec(key: 'exploreUrl', controller: form.exploreUrlCtrl),
          SourceEditLegacyFieldSpec(key: 'bookList', controller: form.exploreBookListCtrl),
          SourceEditLegacyFieldSpec(key: 'name', controller: form.exploreNameCtrl),
          SourceEditLegacyFieldSpec(key: 'author', controller: form.exploreAuthorCtrl),
          SourceEditLegacyFieldSpec(key: 'kind', controller: form.exploreKindCtrl),
          SourceEditLegacyFieldSpec(key: 'wordCount', controller: form.exploreWordCountCtrl),
          SourceEditLegacyFieldSpec(key: 'lastChapter', controller: form.exploreLastChapterCtrl),
          SourceEditLegacyFieldSpec(key: 'intro', controller: form.exploreIntroCtrl),
          SourceEditLegacyFieldSpec(key: 'coverUrl', controller: form.exploreCoverUrlCtrl),
          SourceEditLegacyFieldSpec(key: 'bookUrl', controller: form.exploreBookUrlCtrl),
        ],
        activeFieldController: activeFieldController,
        onFieldActivated: onFieldActivated,
        onShowInsertActions: onShowInsertActions,
      ),
      _buildRuleTabSection(
        title: '详情规则',
        fields: <SourceEditLegacyFieldSpec>[
          SourceEditLegacyFieldSpec(key: 'init', controller: form.infoInitCtrl),
          SourceEditLegacyFieldSpec(key: 'name', controller: form.infoNameCtrl),
          SourceEditLegacyFieldSpec(key: 'author', controller: form.infoAuthorCtrl),
          SourceEditLegacyFieldSpec(key: 'kind', controller: form.infoKindCtrl),
          SourceEditLegacyFieldSpec(key: 'wordCount', controller: form.infoWordCountCtrl),
          SourceEditLegacyFieldSpec(key: 'lastChapter', controller: form.infoLastChapterCtrl),
          SourceEditLegacyFieldSpec(key: 'intro', controller: form.infoIntroCtrl),
          SourceEditLegacyFieldSpec(key: 'coverUrl', controller: form.infoCoverUrlCtrl),
          SourceEditLegacyFieldSpec(key: 'tocUrl', controller: form.infoTocUrlCtrl),
          SourceEditLegacyFieldSpec(key: 'canReName', controller: form.infoCanRenameCtrl),
          SourceEditLegacyFieldSpec(key: 'downloadUrls', controller: form.infoDownloadUrlsCtrl),
        ],
        activeFieldController: activeFieldController,
        onFieldActivated: onFieldActivated,
        onShowInsertActions: onShowInsertActions,
      ),
      _buildRuleTabSection(
        title: '目录规则',
        fields: <SourceEditLegacyFieldSpec>[
          SourceEditLegacyFieldSpec(key: 'preUpdateJs', controller: form.tocPreUpdateJsCtrl, maxLines: 3),
          SourceEditLegacyFieldSpec(key: 'chapterList', controller: form.tocChapterListCtrl),
          SourceEditLegacyFieldSpec(key: 'chapterName', controller: form.tocChapterNameCtrl),
          SourceEditLegacyFieldSpec(key: 'chapterUrl', controller: form.tocChapterUrlCtrl),
          SourceEditLegacyFieldSpec(key: 'formatJs', controller: form.tocFormatJsCtrl, maxLines: 3),
          SourceEditLegacyFieldSpec(key: 'isVolume', controller: form.tocIsVolumeCtrl),
          SourceEditLegacyFieldSpec(key: 'updateTime', controller: form.tocUpdateTimeCtrl),
          SourceEditLegacyFieldSpec(key: 'isVip', controller: form.tocIsVipCtrl),
          SourceEditLegacyFieldSpec(key: 'isPay', controller: form.tocIsPayCtrl),
          SourceEditLegacyFieldSpec(key: 'nextTocUrl', controller: form.tocNextTocUrlCtrl),
        ],
        activeFieldController: activeFieldController,
        onFieldActivated: onFieldActivated,
        onShowInsertActions: onShowInsertActions,
      ),
      _buildRuleTabSection(
        title: '正文规则',
        fields: <SourceEditLegacyFieldSpec>[
          SourceEditLegacyFieldSpec(key: 'content', controller: form.contentContentCtrl, maxLines: 4),
          SourceEditLegacyFieldSpec(key: 'title', controller: form.contentTitleCtrl),
          SourceEditLegacyFieldSpec(key: 'nextContentUrl', controller: form.contentNextContentUrlCtrl),
          SourceEditLegacyFieldSpec(key: 'webJs', controller: form.contentWebJsCtrl, maxLines: 3),
          SourceEditLegacyFieldSpec(key: 'sourceRegex', controller: form.contentSourceRegexCtrl, maxLines: 3),
          SourceEditLegacyFieldSpec(key: 'replaceRegex', controller: form.contentReplaceRegexCtrl, maxLines: 3),
          SourceEditLegacyFieldSpec(key: 'imageStyle', controller: form.contentImageStyleCtrl, maxLines: 3),
          SourceEditLegacyFieldSpec(key: 'imageDecode', controller: form.contentImageDecodeCtrl, maxLines: 3),
          SourceEditLegacyFieldSpec(key: 'payAction', controller: form.contentPayActionCtrl, maxLines: 3),
        ],
        activeFieldController: activeFieldController,
        onFieldActivated: onFieldActivated,
        onShowInsertActions: onShowInsertActions,
      ),
    ];
  }

  static Widget _buildRuleTabSection({
    required String title,
    required List<SourceEditLegacyFieldSpec> fields,
    required TextEditingController? activeFieldController,
    required void Function(String key, TextEditingController controller)
        onFieldActivated,
    required VoidCallback onShowInsertActions,
  }) {
    return SourceEditLegacyRuleTabSection(
      title: title,
      fields: fields,
      activeFieldController: activeFieldController,
      labelBuilder: labelForField,
      onFieldActivated: onFieldActivated,
      onShowInsertActions: onShowInsertActions,
    );
  }

  static String labelForField(String key) {
    return _fieldLabels[key] ?? key;
  }
}
